In [2]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../data/nba.db")

query = """
SELECT COUNT(*) AS total_rows
FROM playoff_games
"""

df = pd.read_sql(query, conn)

display(df)

   total_rows
0        3358

In [3]:
query = """
SELECT
    MIN(GAME_DATE) AS earliest_game,
    MAX(GAME_DATE) AS latest_game
FROM playoff_games
"""

df = pd.read_sql(query, conn)

display(df)

  earliest_game latest_game
0    1984-04-17  2026-05-15

In [3]:
from nba_api.stats.endpoints import leaguegamefinder
from nba_api.stats.endpoints import boxscoresummaryv3

import time

#get all playoff games
games = leaguegamefinder.LeagueGameFinder(
    season_type_nullable='Playoffs'
)

games_df = games.get_data_frames()[0]


games_df = games_df.drop_duplicates(subset=['GAME_ID'])

game_ids = games_df['GAME_ID']



limit = 0

for game_id in game_ids:
    if limit >=5:
        break
    summary = boxscoresummaryv3.BoxScoreSummaryV3(game_id=game_id)
    summary.line_score.get_data_frame()
    limit+=1

KeyError: 0