In [2]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../data/nba.db")

query = """
SELECT COUNT(*) AS total_rows
FROM playoff_games
"""

df = pd.read_sql(query, conn)

display(df)

   total_rows
0        3358

In [3]:
query = """
SELECT
    MIN(GAME_DATE) AS earliest_game,
    MAX(GAME_DATE) AS latest_game
FROM playoff_games
"""

df = pd.read_sql(query, conn)

display(df)

  earliest_game latest_game
0    1984-04-17  2026-05-15